using System.Text.Json;
using System.Text.Json.Serialization;

namespace TarkovSkills.Core;

public sealed record RaidContext(bool Found, bool Active, string Map, string MapId, string? GameVersion, DateTime? StartedAt, DateTime? EndedAt);
public sealed record ContextAnswers(string Execution, string Weather, string TimeOfDay, string Map);
public sealed record PerformanceMetrics([property: JsonPropertyName("sample_count")] int SampleCount, [property: JsonPropertyName("duration_sec")] double DurationSec, [property: JsonPropertyName("average_fps")] double AverageFps, [property: JsonPropertyName("one_percent_low_fps")] double OnePercentLowFps, [property: JsonPropertyName("zero_point_one_percent_low_fps")] double ZeroPointOnePercentLowFps, [property: JsonPropertyName("average_frametime_ms")] double AverageFrametimeMs, [property: JsonPropertyName("p95_frametime_ms")] double P95FrametimeMs, [property: JsonPropertyName("p99_frametime_ms")] double P99FrametimeMs);
public sealed record BenchmarkRun([property: JsonPropertyName("run_id")] string RunId, [property: JsonPropertyName("collected_date")] string CollectedDate, [property: JsonPropertyName("duration_sec")] int DurationSec, [property: JsonPropertyName("app_version")] string AppVersion, [property: JsonPropertyName("system")] object System, [property: JsonPropertyName("settings")] object Settings, [property: JsonPropertyName("context")] object Context, [property: JsonPropertyName("performance")] PerformanceMetrics Performance, [property: JsonPropertyName("warnings")] IReadOnlyList<string> Warnings, [property: JsonPropertyName("submitted")] bool Submitted = false);
public sealed class BenchmarkDocument { [JsonPropertyName("schema_version")] public int SchemaVersion { get; init; } = 1; [JsonPropertyName("runs")] public List<BenchmarkRun> Runs { get; init; } = []; }
public sealed record CommandResult([property: JsonPropertyName("status")] string Status, [property: JsonPropertyName("run_id")] string? RunId = null, [property: JsonPropertyName("map")] string? Map = null, [property: JsonPropertyName("average_fps")] double? AverageFps = null, [property: JsonPropertyName("one_percent_low_fps")] double? OnePercentLowFps = null, [property: JsonPropertyName("zero_point_one_percent_low_fps")] double? ZeroPointOnePercentLowFps = null, [property: JsonPropertyName("p95_frametime_ms")] double? P95FrametimeMs = null, [property: JsonPropertyName("saved_locally")] bool SavedLocally = false, [property: JsonPropertyName("uploaded")] bool Uploaded = false, [property: JsonPropertyName("message")] string? Message = null);
public static class JsonDefaults { public static JsonSerializerOptions Options { get; } = new() { PropertyNamingPolicy = JsonNamingPolicy.SnakeCaseLower, WriteIndented = true, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull }; }
